os: linux
language: node_js
node_js:
  - "10"
  - "12"

branches:
  only:
    - master
    - develop

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/wallet-lib
      branch: master
