os: linux
language: node_js
node_js:
  - '8'
  - "10"

before_install:
  - echo -e "machine github.com\n  login ${GH_TOKEN}" >> ~/.netrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm install

before_script:
  - npm run lint
