dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - "12"
  - "14"

branches:
  only:
    - master
    - develop
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/

install:
  - npm ci
  - cp .env.example .env

script:
  - npm run check-package
  - npm run build:prod
  - npm run test

before_deploy:
  # Add token for @dashevo private npm registry & deployement
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/wallet-lib
      tags: true
