sudo: required
dist: trusty
language: node_js

node_js:
- 'node'

before_install:
- echo -e "machine github.com\n  login ${GH_TOKEN}" >> ~/.netrc
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
- npm install
