dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - "12"
  - "14"

branches:
  only:
    - master
    - develop

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - npm run check-package
  - npm run build:prod
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/wallet-lib
      branch: master
