const logger = require('../../../logger');
const processAddressList = require('./utils/processAddressList');

// This method is called as first thing by the SyncWorker.
// It's only when resolved that the Wallet will be ready (for what SyncWorker do)
// And therefore that's where we need to deal with all necessary step
// such as fetching all UTXO and previous TX.
//
// It should deal with additional addresses generated by a BIP44 Worker if
// fetching here found that we have more addresses that on starting of the sync up.
module.exports = async function initialSyncUp() {
  let generated = -1;

  while (generated !== 0) {
    const addrList = this.getAddressListToSync().map((addr) => addr.address);
    // Due to the events system, we need to handle the fact that we did subscribed to addresses
    // that we had received the transactions and store before
    // being able to release initialSyncUp as ready.
    // When we will move to bloomfilter, that part might be more complex.
    // eslint-disable-next-line no-await-in-loop
    generated = await processAddressList.call(this, addrList);
  }

  logger.silly('SyncWorker - initialSyncUp - Fully synced');
};
